spring:
  application:
    name: forohub
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${SECRET_JWT}