spring:
  application:
    name: forohub
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect